/**
 * Builds supabase/setup/apply-all-migrations.sql: every migration in order, in
 * one transaction, for a one-time manual setup of an EMPTY hosted project
 * (Supabase → SQL Editor → paste → Run) when the Supabase CLI is not used.
 *
 *   pnpm db:setup-sql            # regenerate after adding a migration
 *   pnpm db:setup-sql --check    # fail if the file is out of date (CI)
 *
 * The file also records the migrations in supabase_migrations.schema_migrations
 * (the Supabase CLI's history table), so a later `supabase db push` applies
 * only newer migrations.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = (p: string) => fileURLToPath(new URL(`../../${p}`, import.meta.url));
export const SETUP_SQL = "supabase/setup/apply-all-migrations.sql";

export function buildSetupSql(): string {
  const files = readdirSync(root("supabase/migrations"))
    .filter((f) => /^\d{14}_.+\.sql$/.test(f))
    .sort();
  const parts = files.map((f) => `-- ════════ ${f} ════════\n${readFileSync(root(`supabase/migrations/${f}`), "utf8").trimEnd()}\n`);
  const history = files.map((f) => `  ('${f.slice(0, 14)}', '${f.slice(15, -4)}')`).join(",\n");
  return `-- Generated by scripts/db/build-setup-sql.ts from supabase/migrations/. Do not edit by hand.
--
-- ONE-TIME SETUP OF AN EMPTY SUPABASE PROJECT
-- Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
-- Everything runs in one transaction: if any statement fails, nothing is applied.
-- It refuses to run on a project that already has the platform's tables.
-- Contains schema, security rules and reference data only — no demo or test data.

begin;

do $guard$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name in ('organizations', 'profiles', 'hospital_inputs', 'hospitals')
  ) then
    raise exception 'This project already contains the platform tables. Nothing was changed. Use the Supabase CLI (supabase db push) for later migrations.';
  end if;
end
$guard$;

${parts.join("\n")}
-- ════════ Migration history (read by the Supabase CLI) ════════
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text not null primary key);
alter table supabase_migrations.schema_migrations add column if not exists statements text[];
alter table supabase_migrations.schema_migrations add column if not exists name text;
insert into supabase_migrations.schema_migrations (version, name) values
${history}
on conflict (version) do nothing;

commit;

-- Expected result: "Success. No rows returned".
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sql = buildSetupSql();
  if (process.argv.includes("--check")) {
    const current = readFileSync(root(SETUP_SQL), "utf8");
    if (current !== sql) {
      console.error(`${SETUP_SQL} is out of date. Run \`pnpm db:setup-sql\`.`);
      process.exit(1);
    }
    console.log(`${SETUP_SQL} is up to date.`);
  } else {
    writeFileSync(root(SETUP_SQL), sql);
    console.log(`Wrote ${SETUP_SQL}`);
  }
}
