/**
 * Builds the reference-data migration from the TypeScript input catalog, so
 * database rows can never drift from the calculation engine.
 *
 *   pnpm db:reference-data   # rewrites supabase/migrations/20261008000100_reference_data.sql
 *
 * Applied migrations are immutable: if the catalog changes after deployment,
 * write the change as a new migration instead of editing this file's output.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { INPUT_DEFINITIONS } from "../../src/domain/inputs/catalog";
import { WORKBOOK_DEFAULT_SCENARIO } from "../../src/domain/scenario";

export const DEFAULT_ORGANIZATION_ID = "00000000-0000-4000-8000-000000000001";
export const DEFAULT_ORGANIZATION_NAME = "Elite Hospital";
export const REFERENCE_DATA_MIGRATION = "supabase/migrations/20261008000100_reference_data.sql";

const literal = (value: string | number | null | undefined): string => {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
};

export function buildReferenceDataSql(): string {
  const org = literal(DEFAULT_ORGANIZATION_ID);
  const rows = INPUT_DEFINITIONS.map((d) =>
    [
      org,
      literal(d.key),
      literal(d.group),
      literal(d.label),
      literal(d.unit),
      literal(d.defaultValue),
      literal(d.owner),
      literal(d.note),
      literal(d.source),
    ].join(", "),
  );
  const s = WORKBOOK_DEFAULT_SCENARIO;

  return `-- Generated by scripts/db/reference-data.ts from src/domain/inputs/catalog.ts. Do not edit by hand.
-- Creates the hospital organisation, one row per catalog input (all hospital values NULL except the
-- verified ICU bed count) and the workbook default scenario. Existing values are never overwritten.

insert into public.organizations (id, name)
values (${org}, ${literal(DEFAULT_ORGANIZATION_NAME)})
on conflict (id) do nothing;

insert into public.hospital_inputs
  (organization_id, key, category, label, unit, numeric_value, data_owner, note, source_type)
values
${rows.map((r) => `  (${r})`).join(",\n")}
on conflict (organization_id, key) do update set
  category = excluded.category,
  label = excluded.label,
  unit = excluded.unit,
  data_owner = excluded.data_owner,
  note = excluded.note,
  source_type = excluded.source_type;

insert into public.scenario_assumptions
  (organization_id, scenario_name, occupancy_rate, package_price, savings_level,
   low_savings_pct, mid_savings_pct, high_savings_pct, is_default)
values
  (${org}, 'Workbook default', ${s.occupancyRate}, ${s.packagePrice}, ${literal(s.savingsLevel)},
   ${s.sensitivities.low}, ${s.sensitivities.mid}, ${s.sensitivities.high}, true)
on conflict (organization_id, scenario_name) do nothing;
`;
}

export const WORKBOOK_TEMPLATES_MIGRATION = "supabase/migrations/20261008100100_workbook_templates.sql";

/**
 * Template rows for the Elite / Workbook Value Model, copied into a hospital by
 * enable_workbook_model(). Hospital data starts blank (no invented values);
 * Respiratory Gate assumptions carry their workbook defaults.
 */
export function buildWorkbookTemplatesSql(): string {
  const rows = INPUT_DEFINITIONS.map((d, i) => {
    // The catalog's ICU-bed entry describes Elite's verified public figure; for any
    // other hospital it is ordinary hospital data.
    const generic = d.key === "icu_beds" ? { owner: "ICU / Admissions", note: "Total ICU beds, all ICUs", source: "hospital_data" } : d;
    return [
      literal(d.key),
      literal(d.group),
      literal(d.label),
      literal(d.unit),
      literal(d.source === "rg_assumption" ? d.defaultValue : null),
      literal(generic.owner),
      literal(generic.note),
      literal(generic.source),
      i + 1,
    ].join(", ");
  });
  return `-- Generated by scripts/db/reference-data.ts from src/domain/inputs/catalog.ts. Do not edit by hand.
-- Workbook Value Model input template used by enable_workbook_model().

insert into public.workbook_input_templates
  (key, category, label, unit, default_value, data_owner, note, source_type, sort_order)
values
${rows.map((r) => `  (${r})`).join(",\n")}
on conflict (key) do update set
  category = excluded.category,
  label = excluded.label,
  unit = excluded.unit,
  default_value = excluded.default_value,
  data_owner = excluded.data_owner,
  note = excluded.note,
  source_type = excluded.source_type,
  sort_order = excluded.sort_order;
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  for (const [file, sql] of [
    [REFERENCE_DATA_MIGRATION, buildReferenceDataSql()],
    [WORKBOOK_TEMPLATES_MIGRATION, buildWorkbookTemplatesSql()],
  ] as const) {
    writeFileSync(fileURLToPath(new URL(`../../${file}`, import.meta.url)), sql);
    console.log(`Wrote ${file}`);
  }
}
