-- Generated by scripts/db/reference-data.ts from src/domain/inputs/catalog.ts. Do not edit by hand.
-- Creates the hospital organisation, one row per catalog input (all hospital values NULL except the
-- verified ICU bed count) and the workbook default scenario. Existing values are never overwritten.

insert into public.organizations (id, name)
values ('00000000-0000-4000-8000-000000000001', 'Elite Hospital')
on conflict (id) do nothing;

insert into public.hospital_inputs
  (organization_id, key, category, label, unit, numeric_value, data_owner, note, source_type)
values
  ('00000000-0000-4000-8000-000000000001', 'icu_beds', 'icu_activity', 'ICU beds', 'beds', 50, 'Verified', 'Elite official ICU page (elitehospital.org, 6 Oct 2026)', 'verified_public'),
  ('00000000-0000-4000-8000-000000000001', 'icu_occupancy_rate_actual', 'icu_activity', 'ICU occupancy rate', '%', null, 'ICU / Admissions', 'Annual average occupancy', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'ventilated_patient_days', 'icu_activity', 'Ventilated patient-days', 'patient-days / yr', null, 'ICU', 'Invasive mechanical ventilation days, all ICUs', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'avg_ventilator_days_per_patient', 'icu_activity', 'Average ventilator days per patient', 'days', null, 'ICU', 'Mean duration of invasive ventilation', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'niv_patient_days', 'icu_activity', 'NIV patient-days', 'patient-days / yr', null, 'ICU', 'NIV / CPAP / BiPAP days', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'hfnc_patient_days', 'icu_activity', 'HFNC patient-days', 'patient-days / yr', null, 'ICU', 'High-flow nasal cannula days', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'oxygen_consumption', 'icu_activity', 'Oxygen consumption', 'm³ or units / yr', null, 'Supply chain', 'As purchased (state unit in note)', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'cost_per_ventilator_day', 'unit_costs', 'Cost per ventilator-day', 'EGP', null, 'Finance', 'Consumables + device + direct resources per ventilated day', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'cost_per_niv_day', 'unit_costs', 'Cost per NIV day', 'EGP', null, 'Finance', 'Interfaces, circuits, device cost per NIV day', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'cost_per_hfnc_day', 'unit_costs', 'Cost per HFNC day', 'EGP', null, 'Finance', 'Circuits, humidification, device cost per HFNC day', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'oxygen_spend', 'annual_spend', 'Oxygen spend', 'EGP / yr', null, 'Finance', 'Total medical oxygen purchasing', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'respiratory_consumable_spend', 'annual_spend', 'Respiratory consumable expenditure', 'EGP / yr', null, 'Finance', 'Circuits, HME/HMEF, filters, closed suction, nebulizer kits, interfaces, HFNC circuits, humidification', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'equipment_rental_spend', 'annual_spend', 'Respiratory equipment rental', 'EGP / yr', null, 'Biomedical', 'If applicable', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'equipment_maintenance_spend', 'annual_spend', 'Respiratory equipment maintenance', 'EGP / yr', null, 'Biomedical', 'Service contracts and repairs', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'planned_equipment_purchases', 'annual_spend', 'Planned respiratory equipment purchases', 'EGP / yr', null, 'Biomedical', 'Capital budget for ventilators, NIV, HFNC, humidifiers, transport ventilators', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'respiratory_staffing_spend', 'annual_spend', 'Current respiratory staffing expenditure', 'EGP / yr', null, 'HR / Finance', 'Staff currently delivering respiratory tasks', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'respiratory_overtime_spend', 'annual_spend', 'Overtime expenditure (respiratory-related)', 'EGP / yr', null, 'HR / Finance', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'pft_outsourcing_spend', 'annual_spend', 'PFT outsourcing', 'EGP / yr', null, 'Finance', 'If applicable', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'external_respiratory_services_spend', 'annual_spend', 'External respiratory service expenditure', 'EGP / yr', null, 'Finance', 'If applicable', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'ventilator_circuits_used', 'usage', 'Ventilator circuit usage', 'units / yr', null, 'Supply chain', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'filters_used', 'usage', 'Filter usage', 'units / yr', null, 'Supply chain', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'closed_suction_used', 'usage', 'Closed suction usage', 'units / yr', null, 'Supply chain', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'hfnc_circuits_used', 'usage', 'HFNC circuit usage', 'units / yr', null, 'Supply chain', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'niv_interfaces_used', 'usage', 'NIV interface usage', 'units / yr', null, 'Supply chain', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'respiratory_equipment_inventory', 'equipment', 'Respiratory equipment inventory', 'devices', null, 'Biomedical', 'Ventilators, NIV, HFNC, humidifiers, nebulizers, transport ventilators', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'respiratory_equipment_utilization_rate', 'equipment', 'Respiratory equipment utilization rate', '%', null, 'Biomedical', 'Average in-use time ÷ available time', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'billable_respiratory_activities', 'billing', 'Current billable respiratory activities', 'activities / yr', null, 'Finance / Billing', 'Activities billed today', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'unbilled_eligible_respiratory_activities', 'billing', 'Unbilled eligible respiratory activities', 'activities / yr', null, 'Finance / Billing', 'Performed but not captured (from audit)', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'avg_tariff_per_respiratory_activity', 'billing', 'Average tariff per respiratory activity', 'EGP', null, 'Finance / Billing', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'collection_rate', 'billing', 'Actual collection rate', '%', null, 'Finance', 'Collected ÷ billed', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'pft_annual_tests', 'other_revenue', 'Pulmonary Function Testing — tests per year', 'tests / yr', null, 'Finance', 'Tests a year × hospital PFT tariff. Leave blank until priced.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'pft_price_per_test', 'other_revenue', 'Pulmonary Function Testing — price per test', 'EGP', null, 'Finance', 'Hospital PFT tariff', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'education_annual_participants', 'other_revenue', 'Education Center — participants per year', 'participants / yr', null, 'Finance', 'Participants × course fee. Leave blank until priced.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'education_fee_per_participant', 'other_revenue', 'Education Center — course fee', 'EGP', null, 'Finance', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'future_programs_annual_enrolled', 'other_revenue', 'Future clinical programs — enrolled per year', 'enrolments / yr', null, 'Finance', 'Aggregate count only. Enrolled patients × program fee. Leave blank until priced.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'future_programs_fee', 'other_revenue', 'Future clinical programs — program fee', 'EGP', null, 'Finance', null, 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_rt_salaries', 'operating_cost', 'RT salaries', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_supervisor_salaries', 'operating_cost', 'Supervisor / lead salaries', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_clinical_education', 'operating_cost', 'Clinical education', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_consumables_incremental', 'operating_cost', 'Consumables (incremental)', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_equipment_depreciation', 'operating_cost', 'Equipment depreciation', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_maintenance', 'operating_cost', 'Maintenance', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_documentation_technology', 'operating_cost', 'Documentation / technology', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_training', 'operating_cost', 'Training', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_admin_overhead', 'operating_cost', 'Admin / management overhead', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'opcost_supply_chain_logistics', 'operating_cost', 'Supply chain / logistics', 'EGP / yr', null, 'Finance', 'Annual cost of running the RT service. Enter 0 if not applicable.', 'hospital_data'),
  ('00000000-0000-4000-8000-000000000001', 'days_per_month', 'model_assumptions', 'Days per month', 'days', 30, 'Respiratory Gate', 'Assumption: 30-day month (monthly view only)', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'days_per_year', 'model_assumptions', 'Days per year', 'days', 365, 'Respiratory Gate', 'Assumption: 365-day year', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'occupancy_scenario_1', 'model_assumptions', 'Occupancy scenario 1', '%', 0.6, 'Respiratory Gate', 'Occupancy grid on the Revenue screen', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'occupancy_scenario_2', 'model_assumptions', 'Occupancy scenario 2', '%', 0.7, 'Respiratory Gate', 'Occupancy grid on the Revenue screen', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'occupancy_scenario_3', 'model_assumptions', 'Occupancy scenario 3', '%', 0.8, 'Respiratory Gate', 'Occupancy grid on the Revenue screen', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'occupancy_scenario_4', 'model_assumptions', 'Occupancy scenario 4', '%', 0.9, 'Respiratory Gate', 'Occupancy grid on the Revenue screen', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'price_scenario_1', 'model_assumptions', 'Package price scenario 1', 'EGP / patient-day', 800, 'Respiratory Gate', 'Commercial assumption per occupied ICU respiratory patient-day', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'price_scenario_2', 'model_assumptions', 'Package price scenario 2', 'EGP / patient-day', 1000, 'Respiratory Gate', 'Commercial assumption per occupied ICU respiratory patient-day', 'rg_assumption'),
  ('00000000-0000-4000-8000-000000000001', 'price_scenario_3', 'model_assumptions', 'Package price scenario 3', 'EGP / patient-day', 1200, 'Respiratory Gate', 'Commercial assumption per occupied ICU respiratory patient-day', 'rg_assumption')
on conflict (organization_id, key) do update set
  category = excluded.category,
  label = excluded.label,
  unit = excluded.unit,
  data_owner = excluded.data_owner,
  note = excluded.note,
  source_type = excluded.source_type;

insert into public.scenario_assumptions
  (organization_id, scenario_name, occupancy_rate, package_price, savings_level,
   low_savings_pct, mid_savings_pct, high_savings_pct, is_default)
values
  ('00000000-0000-4000-8000-000000000001', 'Workbook default', 0.8, 1000, 'mid',
   0.05, 0.1, 0.15, true)
on conflict (organization_id, scenario_name) do nothing;
